development:
  adapter: postgresql
  database: point_it_dev
  encoding: unicode
  pool: 5
  timeout: 5000
  username: point_it
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: point_it_test
  pool: 5
  username: point_it
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: point_it_production
  pool: 5
  username: point_it
  password:
